### ISSUE TITLE
issue when syncing chain data

### ISSUE THREAD

**Issue by superisaac** [byteball/byteballcore#115]
When I ran headless-byteball, the error was thrown and process terminates
```
From this point, output will be redirected to /root/.config/headless-byteball/log.txt
To release the terminal, type Ctrl-Z, then 'bg'
/root/headless-byteball/node_modules/byteballcore/storage.js:730
                                        throw Error("different props of "+unit+", mem: "+JSON.stringify(props2)+", db: "+JSON.stringify(props));
                                        ^

Error: different props of 80ftUd7v34yJstagU5EwTu6wyyDW0yRk9XX/K8ZL36Y=, mem: {"unit":"80ftUd7v34yJstagU5EwTu6wyyDW0yRk9XX/K8ZL36Y=","level":3350626,"latest_included_mc_index":3245724,"main_chain_index":3245725,"is_on_main_chain":1,"is_free":1,"is_stable":0,"witnessed_level":3350611,"headers_commission":344,"payload_commission":157,"sequence":"good","author_addresses":["CHNK74ZY66XTYLWB45UES26G3AAS522V"],"witness_list_unit":"oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E="}, db: {"unit":"80ftUd7v34yJstagU5EwTu6wyyDW0yRk9XX/K8ZL36Y=","level":3350626,"latest_included_mc_index":3245724,"main_chain_index":3245725,"is_on_main_chain":1,"is_free":1,"is_stable":0,"witnessed_level":3350611,"headers_commission":344,"payload_commission":157,"sequence":"temp-bad","author_addresses":["CHNK74ZY66XTYLWB45UES26G3AAS522V"],"witness_list_unit":"oj8yEksX9Ubq7lLc+p6F2uyHUuynugeVq4+ikT67X6E="}
    at /root/headless-byteball/node_modules/byteballcore/storage.js:730:12
    at Statement.<anonymous> (/root/headless-byteball/node_modules/byteballcore/sqlite_pool.js:115:6)
```
seems there is a conflict, can any one help me solve this problem please.

**Comment by superisaac** [comment]
the problematic unit is always "80ftUd7v34yJstagU5EwTu6wyyDW0yRk9XX/K8ZL36Y="

**Comment by superisaac** [comment]
It's very odd, I query the database and found the `sequence` to be 'good', but in the error message it's 'temp-bad', can I just delete it?
```
sqlite> select is_stable, sequence from units where unit = '80ftUd7v34yJstagU5EwTu6wyyDW0yRk9XX/K8ZL36Y=';                        0|good
sqlite>
```

**Comment by tarmo888** [comment]
https://github.com/byteball/byteballcore/blob/master/storage.js#L730 looks like this:
```
if (!_.isEqual(props, props2)) {
```
your error shows that on your line 730, you have this
```
throw Error("different props of "+unit+", mem: "+JSON.stringify(props2)+", db: "+JSON.stringify(props));
```
headless-wallet has this dependency
```
"byteballcore": "git+https://github.com/byteball/byteballcore.git",
```

have you tried `npm update`?

**Comment by superisaac** [comment]
@tarmo888  Maybe the problem is here, I just forked this repo to work around a problem of installing sqlite3, and forgot to merge the latest upstream. but currently I met the problem of installing sqlite3 again

**Comment by superisaac** [comment]
@tarmo888 I merged the upstream and reinstalled our docker, it works, thank you!
