### ISSUE TITLE
network.js failed to reroute command to the next peer:  Cannot read property 'responseHandlers' of undefined

### ISSUE THREAD

**Issue by pmiklos** [byteball/byteballcore#12]
My headless-byteball wallet died with the error below (on Jan 31). The byteballcore version was 0.1.35

```
/home/pi/headless-byteball/node_modules/byteballcore/network.js:171
				ws.assocPendingRequests[tag].responseHandlers.forEach(function(rh){
				                            ^

TypeError: Cannot read property 'responseHandlers' of undefined
    at /home/pi/headless-byteball/node_modules/byteballcore/network.js:171:33
    at /home/pi/headless-byteball/node_modules/byteballcore/network.js:251:11
    at tryFindNextPeer (/home/pi/headless-byteball/node_modules/byteballcore/network.js:266:3)
    at findNextPeer (/home/pi/headless-byteball/node_modules/byteballcore/network.js:249:2)
    at EventEmitter.<anonymous> (/home/pi/headless-byteball/node_modules/byteballcore/network.js:255:4)
    at EventEmitter.g (events.js:291:16)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at /home/pi/headless-byteball/node_modules/byteballcore/network.js:577:13
    at /home/pi/headless-byteball/node_modules/byteballcore/network.js:203:3
```

**Comment by tonyofbyteball** [comment]
fixed by https://github.com/byteball/byteballcore/commit/bac1431cdb7bca2a4242ef8e4b3c57110bf43819
