### ISSUE TITLE
Cannot read property 'connectionConfig' of undefined

### ISSUE THREAD

**Issue by pmiklos** [byteball/byteballcore#84]
The latest git version of byteballcore fails on startup when used with mysql. The issue is in function `initUnstableUnit` where `db.escape` is used as a mapper function, but the escape function refers to `this` which in this usage gets the wrong context:

```javascript
"SELECT parent_unit, child_unit FROM parenthoods WHERE child_unit IN("+Object.keys(assocUnstableUnits).map(db.escape)+")",
```

the fix is converting it to a function call: 
```javascript
.map(function() { return db.escape(); })
```

The Error:
```
node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'connectionConfig' of undefined
    at Pool.escape (node_modules/mysql/lib/Pool.js:281:42)
    at Array.map (<anonymous>)
    at node_modules/byteballcore/storage.js:1248:108
    at Query._callback (node_modules/byteballcore/mysql_pool.js:43:4)
    at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)

```

**Comment by tonyofbyteball** [comment]
the above commit should be a better fix, we use .map(db.escape) quite often

**Comment by tonyofbyteball** [comment]
Does the issue persist in the most recent version?  I don't reproduce it now.

**Comment by pmiklos** [comment]
not sure to be honest, I switched back to using SQLite. But I don't remember this issue coming up a couple of months ago when I still used MySQL.
